import type { InventoryItem } from "../_types";

export const INITIAL_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: "inv-1",
    title: "OEM Skincare Daily Anti-Aging Face Wash",
    variant: "100ml / Default",
    swatch: "bg-gradient-to-br from-neutral-300 to-neutral-500",
    sku: "SKU-FACE-01",
    unavailable: 0,
    committed: 24,
    available: 2976,
    onHand: 3000,
    incoming: 500,
  },
  {
    id: "inv-2",
    title: "OEM KORMESIC Organic Anti-Acne Facial Cleanser",
    variant: "Foaming Gel 150ml",
    swatch: "bg-gradient-to-br from-sky-100 to-blue-200",
    sku: "SKU-KORM-02",
    unavailable: 5,
    committed: 12,
    available: 983,
    onHand: 1000,
    incoming: 0,
  },
  {
    id: "inv-3",
    title: "Korea Private Label Pink Rose Creamy Jelly Cleanser",
    variant: "120ml / Tube",
    swatch: "bg-gradient-to-br from-pink-100 to-rose-200",
    sku: "SKU-ROSE-03",
    unavailable: 0,
    committed: 45,
    available: 454,
    onHand: 499,
    incoming: 200,
  },
  {
    id: "inv-4",
    title: "FATAZEN Deep Moisturizing Foaming Cleanser",
    variant: "200ml / Pump",
    swatch: "bg-gradient-to-br from-rose-100 to-pink-200",
    sku: "SKU-FATA-04",
    unavailable: 10,
    committed: 8,
    available: 981,
    onHand: 999,
    incoming: 0,
  },
  {
    id: "inv-5",
    title: "Natural Neem Pimple Control Cleansing Gel",
    variant: "100ml / Gel",
    swatch: "bg-gradient-to-br from-emerald-100 to-green-200",
    sku: "SKU-NEEM-05",
    unavailable: 0,
    committed: 15,
    available: 985,
    onHand: 1000,
    incoming: 350,
  },
  {
    id: "inv-6",
    title: "Purifying Neem Face Wash",
    variant: "150ml",
    swatch: "bg-gradient-to-br from-lime-100 to-emerald-200",
    sku: "SKU-HIMA-06",
    unavailable: 0,
    committed: 50,
    available: 950,
    onHand: 1000,
    incoming: 1000,
  },
  {
    id: "inv-7",
    title: "Private Label Acne Foaming Wash Cream",
    variant: "80ml / Sensitive",
    swatch: "bg-gradient-to-br from-teal-100 to-cyan-200",
    sku: "SKU-ACNE-07",
    unavailable: 2,
    committed: 18,
    available: 980,
    onHand: 1000,
    incoming: 0,
  },
  {
    id: "inv-8",
    title: "Private Label Skin Care Simple Face Wash",
    variant: "150ml / Normal",
    swatch: "bg-gradient-to-br from-rose-100 to-pink-200",
    sku: "SKU-SMPL-08",
    unavailable: 0,
    committed: 30,
    available: 969,
    onHand: 999,
    incoming: 250,
  },
  {
    id: "inv-9",
    title: "Simple Daily Skin Detox Purifying Face Wash",
    variant: "150ml / Detox",
    swatch: "bg-gradient-to-br from-amber-100 to-orange-200",
    sku: "SKU-DTX-09",
    unavailable: 0,
    committed: 10,
    available: 89,
    onHand: 99,
    incoming: 150,
  },
  {
    id: "inv-10",
    title: "Japanese Skincare Vitamin C Enzyme Facial Wash",
    variant: "100g / Powder",
    swatch: "bg-gradient-to-br from-yellow-100 to-amber-200",
    sku: "SKU-VITC-10",
    unavailable: 0,
    committed: 6,
    available: 44,
    onHand: 50,
    incoming: 100,
  },
  {
    id: "inv-11",
    title: "Face Wash Deep KOJIC Facial Cleanser",
    variant: "100g / Cream",
    swatch: "bg-gradient-to-br from-orange-100 to-amber-200",
    sku: "SKU-KOJC-11",
    unavailable: 4,
    committed: 12,
    available: 96,
    onHand: 112,
    incoming: 200,
  },
  {
    id: "inv-12",
    title: "Private Label KORMESIC Acne Treatment Foaming",
    variant: "120ml / Foaming",
    swatch: "bg-gradient-to-br from-amber-200 to-yellow-300",
    sku: "SKU-TRMT-12",
    unavailable: 0,
    committed: 40,
    available: 1160,
    onHand: 1200,
    incoming: 0,
  },
];
