import type { Order } from "../_types";

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-1024",
    orderNumber: "#1024",
    date: "Today at 2:45 PM",
    customer: {
      name: "Sophia Martinez",
      email: "sophia.m@example.com",
    },
    channel: "Online Store",
    total: 342.5,
    paymentStatus: "paid",
    fulfillmentStatus: "unfulfilled",
    itemsCount: 3,
    deliveryMethod: "Standard Shipping",
    tags: ["VIP", "Express"],
  },
  {
    id: "ord-1023",
    orderNumber: "#1023",
    date: "Today at 11:20 AM",
    customer: {
      name: "Liam O'Connor",
      email: "liam.oc@example.com",
    },
    channel: "Online Store",
    total: 89.0,
    paymentStatus: "paid",
    fulfillmentStatus: "fulfilled",
    itemsCount: 1,
    deliveryMethod: "Local Delivery",
    tags: ["First-time"],
  },
  {
    id: "ord-1022",
    orderNumber: "#1022",
    date: "Yesterday at 6:15 PM",
    customer: {
      name: "Emma Watson",
      email: "emma.watson@example.com",
    },
    channel: "POS - Soho",
    total: 540.0,
    paymentStatus: "paid",
    fulfillmentStatus: "fulfilled",
    itemsCount: 4,
    deliveryMethod: "In-store Pickup",
  },
  {
    id: "ord-1021",
    orderNumber: "#1021",
    date: "Sep 22 at 9:02 PM",
    customer: {
      name: "Noah Chen",
      email: "noah.chen@example.com",
    },
    channel: "Online Store",
    total: 124.99,
    paymentStatus: "pending",
    fulfillmentStatus: "unfulfilled",
    itemsCount: 2,
    deliveryMethod: "Standard Shipping",
    tags: ["Follow-up"],
  },
  {
    id: "ord-1020",
    orderNumber: "#1020",
    date: "Sep 22 at 4:30 PM",
    customer: {
      name: "Isabella Rossi",
      email: "isabella.r@example.com",
    },
    channel: "Online Store",
    total: 75.0,
    paymentStatus: "refunded",
    fulfillmentStatus: "restocked",
    itemsCount: 1,
    deliveryMethod: "Standard Shipping",
  },
  {
    id: "ord-1019",
    orderNumber: "#1019",
    date: "Sep 21 at 1:12 PM",
    customer: {
      name: "Lucas Bennett",
      email: "lucas.b@example.com",
    },
    channel: "Online Store",
    total: 210.0,
    paymentStatus: "paid",
    fulfillmentStatus: "partial",
    itemsCount: 3,
    deliveryMethod: "Express Courier",
  },
];
